### ISSUE TITLE
New version 1.6.1 crashes

### ISSUE THREAD

**Issue by emtreulapollaguera** [sideswap-io/sideswapclient#49]
```
type: crash
osVersion: google/shiba/shiba:14/AP2A.240905.003/2024091900:user/release-keys
package: io.sideswap:2115
process: io.sideswap
processUptime: 111 + 216 ms
installer: dev.imranr.obtainium

java.lang.UnsatisfiedLinkError: Unable to load library 'sideswap_client':
dlopen failed: library "libgreen_gdk_java.so" not found: needed by /data/app/~~6gZYBoCLKsfOb4gp9uofiQ==/io.sideswap--_ET0Wthqyj-GzxDrcDpJg==/lib/arm64/libsideswap_client.so in namespace clns-3
dlopen failed: library "libgreen_gdk_java.so" not found: needed by /data/app/~~6gZYBoCLKsfOb4gp9uofiQ==/io.sideswap--_ET0Wthqyj-GzxDrcDpJg==/lib/arm64/libsideswap_client.so in namespace clns-3
dlopen failed: library "libgreen_gdk_java.so" not found: needed by /data/app/~~6gZYBoCLKsfOb4gp9uofiQ==/io.sideswap--_ET0Wthqyj-GzxDrcDpJg==/lib/arm64/libsideswap_client.so in namespace clns-3
Native library (android-aarch64/libsideswap_client.so) not found in resource path (.)
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:325)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:481)
	at com.sun.jna.Library$Handler.<init>(Library.java:197)
	at com.sun.jna.Native.load(Native.java:618)
	at com.sun.jna.Native.load(Native.java:592)
	at uniffi.sideswap_jade.UniffiLib$Companion$INSTANCE$2.invoke(sideswap_jade.kt:1992)
	at uniffi.sideswap_jade.UniffiLib$Companion$INSTANCE$2.invoke(sideswap_jade.kt:779)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at uniffi.sideswap_jade.UniffiLib$Companion.getINSTANCE$app_fullRelease(sideswap_jade.kt:779)
	at uniffi.sideswap_jade.BleClient.<init>(sideswap_jade.kt:1790)
	at io.sideswap.JadeBleKt.startBle(JadeBle.kt:547)
	at io.sideswap.MainActivity.onCreate(MainActivity.kt:50)
	at android.app.Activity.performCreate(Activity.java:9013)
	at android.app.Activity.performCreate(Activity.java:8991)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1531)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3986)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4184)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:114)
	at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:231)
	at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:152)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:93)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2602)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8623)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
	Suppressed: java.lang.UnsatisfiedLinkError: dlopen failed: library "libgreen_gdk_java.so" not found: needed by /data/app/~~6gZYBoCLKsfOb4gp9uofiQ==/io.sideswap--_ET0Wthqyj-GzxDrcDpJg==/lib/arm64/libsideswap_client.so in namespace clns-3
		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:213)
		... 30 more
	Suppressed: java.lang.UnsatisfiedLinkError: dlopen failed: library "libgreen_gdk_java.so" not found: needed by /data/app/~~6gZYBoCLKsfOb4gp9uofiQ==/io.sideswap--_ET0Wthqyj-GzxDrcDpJg==/lib/arm64/libsideswap_client.so in namespace clns-3
		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:226)
		... 30 more
	Suppressed: java.lang.UnsatisfiedLinkError: dlopen failed: library "libgreen_gdk_java.so" not found: needed by /data/app/~~6gZYBoCLKsfOb4gp9uofiQ==/io.sideswap--_ET0Wthqyj-GzxDrcDpJg==/lib/arm64/libsideswap_client.so in namespace clns-3
		at java.lang.Runtime.loadLibrary0(Runtime.java:1081)
		at java.lang.Runtime.loadLibrary0(Runtime.java:1003)
		at java.lang.System.loadLibrary(System.java:1765)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:240)
		... 30 more
	Suppressed: java.io.IOException: Native library (android-aarch64/libsideswap_client.so) not found in resource path (.)
		at com.sun.jna.Native.extractFromResourcePath(Native.java:1141)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:297)
		... 30 more
```
[Uploading SideSwap log e43cf4a8d2b5.txt…]()

**Comment by sideswap-io** [comment]
This should already be fixed, the APK files have been replaced with the corrected builds. Thanks for reporting this.
